name: CI - Native

on: 
  workflow_call:
  pull_request:
    paths:
      - "taskdb/**"

jobs:
  set-taskdb:
    runs-on: ubuntu-latest
    outputs:
      taskdb: ${{ steps.check_file.outputs.taskdb }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0


  build-test-native:
    name: Build and test native
    needs: set-taskdb
    uses: ./.github/workflows/ci-build-test-reusable.yml
    with:
      version_name: "native"
      version_toolchain: "nightly-2024-04-17"
      taskdb: ${{ needs.set-taskdb.outputs.taskdb }}

  integration-test-native:
    name: Run integration tests on native
    needs: set-taskdb
    uses: ./.github/workflows/ci-integration-reusable.yml
    with:
      version_name: "native"
      version_toolchain: "nightly-2024-04-17"
      taskdb: ${{ needs.set-taskdb.outputs.taskdb }}
